Upgrade Pack to latest version 0.26.0
The very old pack version is not compatible with the latest builder buildpacks and causes errors like

```
ERROR: failed to build: validating stack mixins: buildpack paketo-buildpacks/bundle-install@0.5.0 does not support stack io.buildpacks.stacks.bionic
```